version: 2.1
jobs:
  lint:
    docker:
      - image: cimg/node:18.19.0
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
  test:
    docker:
      - image: cimg/node:18.19.0
    steps:
      - checkout
      - run: npm ci
      - run: npm test

workflows:
  ci:
    jobs:
      - lint
      - test
